# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: namecheap-ddns-updater
metadata:
    template: azd-init@1.31.2
services:
    namecheap-ddns-updater:
        project: .
        host: containerapp
        language: python
        docker:
            path: Dockerfile
            platform: linux/amd64
        service:
            image: namecheap-ddns-updater
            env:
                APPLICATIONINSIGHTS_CONNECTION_STRING: ${APPLICATION_INSIGHTS_CONNECTION_STRING}
                PORT: "80"
infra:
    template: infra/main.bicep
